### ISSUE TITLE
3pts Expand login route to accept email OR username OR phone number for valid login @fchikwekwe @thecodingsophist

### ISSUE THREAD

**Issue by fchikwekwe** [carfew/carfew#32]
@fchikwekwe @thecodingsophist

**Comment by thecodingsophist** [comment]
@fchikwekwe should access to the login route be in the order of 1) email 2) username 3 phone number or can it be in pretty much any order?

**Comment by fchikwekwe** [comment]
It might be better if the order is 1) username 2) email 3)phone number, but I think any order should work as long as we are validating correctly.
