### ISSUE TITLE
1pt Write the Ride Model @lowewenzel @fchikwekwe

### ISSUE THREAD

**Issue by fchikwekwe** [carfew/carfew#6]
@lowewenzel

**Comment by lowewenzel** [comment]
Base is done. Will update and keep open as controller progresses.

**Comment by fchikwekwe** [comment]
Updated Ride Model with @lowewenzel

**Comment by fchikwekwe** [comment]
This is the kind of task that can always be adjusted. I'm gonna close it. We can reopen if there are major changes needed.
